development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: <%= ENV["POSTGRES_DB"] %>
  username: <%= ENV["POSTGRES_USERNAME"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: <%= ENV["POSTGRES_HOST"] %>
  port: <%= ENV["POSTGRES_PORT"] %>